USE [master]
GO

/****** Object:  Database [men_pers]    Script Date: 08.11.2020 12:41:28 ******/
CREATE DATABASE [men_pers]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'men_pers', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\men_pers.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'men_pers_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\men_pers_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [men_pers] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [men_pers].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [men_pers] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [men_pers] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [men_pers] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [men_pers] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [men_pers] SET ARITHABORT OFF 
GO

ALTER DATABASE [men_pers] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [men_pers] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [men_pers] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [men_pers] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [men_pers] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [men_pers] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [men_pers] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [men_pers] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [men_pers] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [men_pers] SET  DISABLE_BROKER 
GO

ALTER DATABASE [men_pers] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [men_pers] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [men_pers] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [men_pers] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [men_pers] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [men_pers] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [men_pers] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [men_pers] SET RECOVERY FULL 
GO

ALTER DATABASE [men_pers] SET  MULTI_USER 
GO

ALTER DATABASE [men_pers] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [men_pers] SET DB_CHAINING OFF 
GO

ALTER DATABASE [men_pers] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [men_pers] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [men_pers] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [men_pers] SET QUERY_STORE = OFF
GO

USE [men_pers]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [men_pers] SET  READ_WRITE 
GO

