USE [master]
GO

/****** Object:  Database [Razrab_Andryuschenko]    Script Date: 01.12.2020 21:40:02 ******/
CREATE DATABASE [Razrab_Andryuschenko]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Razrab_Andryuschenko', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Razrab_Andryuschenko.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Razrab_Andryuschenko_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Razrab_Andryuschenko_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Razrab_Andryuschenko] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Razrab_Andryuschenko].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Razrab_Andryuschenko] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Razrab_Andryuschenko] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Razrab_Andryuschenko] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Razrab_Andryuschenko] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Razrab_Andryuschenko] SET ARITHABORT OFF 
GO

ALTER DATABASE [Razrab_Andryuschenko] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Razrab_Andryuschenko] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Razrab_Andryuschenko] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Razrab_Andryuschenko] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Razrab_Andryuschenko] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Razrab_Andryuschenko] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Razrab_Andryuschenko] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Razrab_Andryuschenko] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Razrab_Andryuschenko] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Razrab_Andryuschenko] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Razrab_Andryuschenko] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Razrab_Andryuschenko] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Razrab_Andryuschenko] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Razrab_Andryuschenko] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Razrab_Andryuschenko] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Razrab_Andryuschenko] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Razrab_Andryuschenko] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Razrab_Andryuschenko] SET RECOVERY FULL 
GO

ALTER DATABASE [Razrab_Andryuschenko] SET  MULTI_USER 
GO

ALTER DATABASE [Razrab_Andryuschenko] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Razrab_Andryuschenko] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Razrab_Andryuschenko] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Razrab_Andryuschenko] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Razrab_Andryuschenko] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Razrab_Andryuschenko] SET QUERY_STORE = OFF
GO

USE [Razrab_Andryuschenko]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Razrab_Andryuschenko] SET  READ_WRITE 
GO

